FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Mimic_Hopscotch:
      id: 3
      type: Mimic
  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Mimic_Hopscotch: RT + A.on_pressed
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 1, 2]
    qs: [
      [],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
      [0., 1.0, -2.0, 0., 1.0, -2.0, 0., 1.0, -2.0, 0., 1.0, -2.0],
    ]
  Mimic_Hopscotch:
    transitions:
      Passive: LT + B.on_pressed

    motion_file: config/policy/mimic/sys_id_hopscotch/params/sys_id_hopscotch_new.npz
    policy_dir: config/policy/mimic/sys_id_hopscotch/
    time_start: 0.0
    time_end: 1000.0
    end_state: Passive
